CREATE TABLE app_users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50 CHAR) NOT NULL,
    email VARCHAR2(255 CHAR) NOT NULL,
    password_hash VARCHAR2(255 CHAR) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

ALTER TABLE app_users ADD CONSTRAINT uk_app_users_username UNIQUE (username);
ALTER TABLE app_users ADD CONSTRAINT uk_app_users_email UNIQUE (email);

CREATE TABLE jobs (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    hourly_rate NUMBER(10, 2) NOT NULL,
    color_tag VARCHAR2(20 CHAR),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_jobs_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE TABLE shifts (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    job_id NUMBER NOT NULL,
    date_value DATE NOT NULL,
    start_time TIMESTAMP(6) NOT NULL,
    end_time TIMESTAMP(6) NOT NULL,
    tips NUMBER(10, 2) DEFAULT 0 NOT NULL,
    premiums NUMBER(10, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_shifts_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT fk_shifts_job FOREIGN KEY (job_id) REFERENCES jobs(id)
);

CREATE TABLE expenses (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    date_value DATE NOT NULL,
    amount NUMBER(10, 2) NOT NULL,
    category VARCHAR2(120 CHAR) NOT NULL,
    note VARCHAR2(300 CHAR),
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_expenses_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE INDEX idx_jobs_user_id ON jobs(user_id);
CREATE INDEX idx_shifts_user_id ON shifts(user_id);
CREATE INDEX idx_shifts_job_id ON shifts(job_id);
CREATE INDEX idx_expenses_user_id ON expenses(user_id);
