CREATE TABLE refresh_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_id VARCHAR2(100 CHAR) NOT NULL,
    user_id NUMBER NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    revoked NUMBER(1) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_refresh_tokens_token_id UNIQUE (token_id),
    CONSTRAINT fk_refresh_tokens_user FOREIGN KEY (user_id) REFERENCES app_users(id)
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);
