CREATE TABLE user_settings (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    name VARCHAR2(100 CHAR) NOT NULL,
    country VARCHAR2(2 CHAR) NOT NULL,
    tax_rate NUMBER(5, 2) DEFAULT 0 NOT NULL,
    insurance_rate NUMBER(5, 2) DEFAULT 0 NOT NULL,
    other_deductions NUMBER(5, 2) DEFAULT 0 NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_user_settings_user FOREIGN KEY (user_id) REFERENCES app_users(id),
    CONSTRAINT uk_user_settings_user_id UNIQUE (user_id)
);
